# Generated by Django 2.0.5 on 2019-02-28 18:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activityID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Service Learning', 'Service Learning'), ('Assisting Developing Country', 'Assisting Developing Country'), ('Virtual', 'Virtual'), ('Environmental', 'Environmental'), ('Emergency Service', 'Emergency Service'), ('Educational', 'Educational'), ('Corporate', 'Corporate'), ('Event', 'Event'), ('Social/Welfare', 'Social/Welfare')], max_length=30)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
