# Generated by Django 2.0.5 on 2019-03-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunnet', '0004_auto_20190228_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
