# Generated by Django 2.0.5 on 2019-03-10 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunnet', '0005_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Service Learning', 'Service Learning'), ('Assisting Developing Country', 'Assisting Developing Country'), ('Virtual', 'Virtual'), ('Community', 'Community'), ('Environmental', 'Environmental'), ('Emergency Service', 'Emergency Service'), ('Educational', 'Educational'), ('Corporate', 'Corporate'), ('Event', 'Event'), ('Social/Welfare', 'Social/Welfare')], max_length=30)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
