# Generated by Django 2.1.7 on 2019-04-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunnet', '0008_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
