# Generated by Django 2.0.5 on 2019-04-19 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunnet', '0011_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='applied_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
